import { Inter } from "next/font/google";
import { Roboto_Slab } from "next/font/google";
import "@/styles/globals.css";
import {config} from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "FamRecipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bglight h-full`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
